// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-categories.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
import { categories } from "npm:@/data/curriculum";
var list_categories_default = defineTool({
  name: "list_categories",
  title: "List learning categories",
  description: "List CareerSourcer's learning categories and their branches (id, title, featured status, lesson count).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const summary = categories.map((c) => ({
      id: c.id,
      title: c.title,
      description: c.description,
      branches: c.branches.map((b) => ({
        id: b.id,
        title: b.title,
        tagline: b.tagline,
        featured: b.featured,
        lessons: b.lessons.length
      }))
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: { categories: summary }
    };
  }
});

// src/lib/mcp/tools/get-branch.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
import { categories as categories2 } from "npm:@/data/curriculum";
var get_branch_default = defineTool2({
  name: "get_branch",
  title: "Get branch details",
  description: "Get a branch (learning track) with its full lesson list \u2014 titles, intros, video URLs, and challenges.",
  inputSchema: {
    categoryId: z2.string().describe("Category id, e.g. 'technology'."),
    branchId: z2.string().describe("Branch id, e.g. 'web-development'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ categoryId, branchId }) => {
    const category = categories2.find((c) => c.id === categoryId);
    const branch = category?.branches.find((b) => b.id === branchId);
    if (!branch) {
      return {
        content: [{ type: "text", text: `Branch not found: ${categoryId}/${branchId}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(branch, null, 2) }],
      structuredContent: { branch }
    };
  }
});

// src/lib/mcp/tools/get-my-progress.ts
import { createClient } from "npm:@supabase/supabase-js@^2.106.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_my_progress_default = defineTool3({
  name: "get_my_progress",
  title: "Get my progress",
  description: "Get the signed-in user's CareerSourcer progress: selected path, completed sessions, current streak, and streak days.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("user_progress").select("selected_path, completed_sessions, streak_current, streak_last_date, streak_days").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const progress = data ?? {
      selected_path: null,
      completed_sessions: [],
      streak_current: 0,
      streak_last_date: null,
      streak_days: []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(progress, null, 2) }],
      structuredContent: { progress }
    };
  }
});

// src/lib/mcp/tools/search-pool.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.106.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var search_pool_default = defineTool4({
  name: "search_pool",
  title: "Search collaboration pool",
  description: "Search the CareerSourcer collaboration pool for other users. Optionally filter by branch id (e.g. 'web-development') or a free-text query matched against display name, headline, and bio.",
  inputSchema: {
    branch: z3.string().nullable().describe("Optional branch id to filter by (e.g. 'game-development')."),
    query: z3.string().nullable().describe("Optional free-text search over name/headline/bio."),
    limit: z3.number().int().min(1).max(50).nullable().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ branch, query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    let q = supabase.from("pool_profiles").select("user_id, display_name, headline, bio, branches, looking_for, contact_link, updated_at").order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (branch) q = q.contains("branches", [branch]);
    if (query) q = q.or(`display_name.ilike.%${query}%,headline.ilike.%${query}%,bio.ilike.%${query}%`);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profiles: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/upsert-pool-profile.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.106.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var upsert_pool_profile_default = defineTool5({
  name: "upsert_my_pool_profile",
  title: "Create or update my pool profile",
  description: "Create or update the signed-in user's collaboration pool profile so others can find them.",
  inputSchema: {
    display_name: z4.string().min(1).max(60),
    headline: z4.string().max(120).nullable(),
    bio: z4.string().max(600).nullable(),
    branches: z4.array(z4.string()).describe("Branch ids the user is interested in."),
    looking_for: z4.string().max(300).nullable(),
    contact_link: z4.string().max(300).nullable().describe("URL, email, or handle.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    const { data, error } = await supabase.from("pool_profiles").upsert(
      {
        user_id: ctx.getUserId(),
        display_name: input.display_name,
        headline: input.headline,
        bio: input.bio,
        branches: input.branches,
        looking_for: input.looking_for,
        contact_link: input.contact_link
      },
      { onConflict: "user_id" }
    ).select().maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: "Pool profile saved." }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vgpeuihrkwwrckhzoemw";
var mcp_default = defineMcp({
  name: "careersourcer-mcp",
  title: "CareerSourcer MCP",
  version: "0.1.0",
  instructions: "Tools for CareerSourcer: browse learning categories/branches, read the signed-in user's progress and streak, and search or update collaboration pool profiles.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_categories_default, get_branch_default, get_my_progress_default, search_pool_default, upsert_pool_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
